### ISSUE TITLE
Empty list of languages

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/plugin-typed-captions#12]
Hi,

After installing the plugin, the list of available languages is empty. (although i did what was suggested here : https://github.com/bigbluebutton/plugin-typed-captions/issues/9#issue-2858044492)

See screen recording below :

https://github.com/user-attachments/assets/69d66297-f55c-47f1-b8f9-8875d33baaa1

Kind regards,
Thierry

**Comment by pinhaum** [comment]
Hello @pielonet 

Could you please send me some additional info like your bigbluebutton version, the plugin version and also a screenshot of the `settings.yml` file, specifically the section under `public.app.audioCaptions`?

With this I can better investigate the cause and find a definitive solution so that this does not happen again.

**Comment by antobinary** [comment]
Note: @pinhaum just updated the Readme https://github.com/bigbluebutton/plugin-typed-captions/pull/13
High likelyhood that this issue can now be closed. Just awaiting @pielonet 's confirmation.

**Comment by pielonet** [comment]
Hi @pinhaum,

I still have an empty list of languages.

Here is the content of `/etc/bigbluebutton/bbb-html5.yml`

```
public:
  kurento:
    wsUrl: wss://bbb.example.com/bbb-webrtc-sfu
    pagination:
      desktopPageSizes:
        moderator: "9"
        viewer: "9"
    skipVideoPreviewIfPreviousDevice: false
  # for BBB 2.5 or later
  pads:
    url: 'https://bbb.example.com//pad'
  media:
    sipjsHackViaWs: true
    stunTurnServersFetchAddress: 'https://bbb.example.com/bigbluebutton/api/stuns'
    sip_ws_host: 'bbb.example.com/'
    livekit:
      url: wss://bbb.example.com//livekit
    transparentListenOnly: true
  clientLog:
    #server: { enabled: false, level: info }
    #console: { enabled: true, level: debug }
    external:
      enabled: true
      level: info
      url: https://bbb.example.com/html5Log
      method: POST
      throttleInterval: 400
      flushOnClose: true
      logTag: ''
  poll:
    maxCustom: "10"
    maxTypedAnswerLength: "60"
    allowDragAndDropFile: true
  app:
    skipCheck: true
    skipEchoTestIfPreviousDevice: true
    listenOnlyMode: false
    transparentListenOnly: true
    helpLink: https://bbb.example.com//appsdocs/categories/visio-agents
    clientTitle: Visio-test
    basename: '/bbb-4/html5client'
    bbbWebBase: 'https://bbb.example.com//bigbluebutton'
    learningDashboardBase: 'https://bbb.example.com//earning-analytics-dashboard'
    emojiRain:
      enabled: true
    audioCaptions:
      enabled: true
      language:
        available:
          - de-DE
          - en-US
          - fr-FR
          - es-ES
  presentation:
    allowDownloadable: true
    uploadEndpoint: 'https://bbb.example.com/bigbluebutton/presentation/upload'
  layout:
    showSessionDetailsOnJoin: false
```
